# Generated by Django 4.2.3 on 2023-09-13 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(default='Subject placeholder', max_length=512)),
                ('recipients', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
