# Generated by Django 4.2.3 on 2023-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdata',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
