# Generated by Django 4.2.3 on 2023-08-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hostdata_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdata',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
