# Generated by Django 4.2.3 on 2023-09-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hostdata_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hostdata',
            index=models.Index(models.F('ip'), name='ip_idx'),
        ),
    ]
