# Generated by Django 4.2.3 on 2023-09-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hostdata_ip_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hostdata',
            name='ip_idx',
        ),
        migrations.AlterField(
            model_name='hostdata',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, unique=True),
        ),
    ]
